name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - 'feature/**'
      - 'staging/4*'

env:
  PYTHON_VERSION: 3.10.x

jobs:
  validate-models:
    name: CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dev/

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Check black
      if: always()
      run: make check-black

    - name: Check isort
      if: always()
      run: make check-isort

    - name: Check flake8
      if: always()
      run: make flake8

    - name: Check mypy
      if: always()
      run: make mypy

    - name: Check pyupgrade
      if: always()
      run: make pyupgrade

    - name: Validate models.yml
      if: always()
      run: make validate-models
